apiVersion: v1
kind: ConfigMap
metadata:
  name: version-config
  namespace: {{ .Values.environment }}
  labels:
    app: version
data:
  MYSQL_LB: version-db-svc
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: version
  MYSQL_USER: root
  MYSQL_PASSWORD: password
