apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: back
      app: mysql-db
  minReadySeconds: 10
#  strategy:
#    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-db
        role: db
        tier: back
    spec:
      containers:
      - image: moazrefat/jenkins-docker-labs:db-project
        name: mysql-db
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          protocol: TCP
        envFrom:
          - configMapRef:
              name: mysql-config
