apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.environment }}
  labels:
    role: db
    tier: back
#    app: mysql-db
  name: mysql-db-svc
spec:
#  type: NodePort
  # type: LoadBalancer
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql-db
