apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.employees.loadbalancer }}
  namespace: {{ .Values.environment }}
  labels:
    app: employees
spec:
#  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  namespace: {{ .Values.environment }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http: 
      paths:
      - path: /api/hostname
        backend:
          serviceName: {{ .Values.employees.loadbalancer }}
          servicePort: {{ .Values.employees.port }}
      - path: /api/details
        backend:
          serviceName: {{ .Values.employees.loadbalancer }}
          servicePort: {{ .Values.employees.port }}
      - path: /api/register
        backend:
          serviceName: {{ .Values.employees.loadbalancer }}
          servicePort: {{ .Values.employees.port }}
      - path: /api/health
        backend:
          serviceName: {{ .Values.employees.loadbalancer }}
          servicePort: {{ .Values.employees.port }}
      - path: /api/info
        backend:
          serviceName: {{ .Values.employees.loadbalancer }}
          servicePort: {{ .Values.employees.port }}
      - path: /welcome
        backend:
          serviceName: {{ .Values.employees.loadbalancer }}
          servicePort: {{ .Values.employees.port }}