apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: employees-hpa
  namespace: {{ .Values.environment }}
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.employees.name }}
  targetCPUUtilizationPercentage: 70
