apiVersion: v1
kind: ConfigMap
metadata:
  name: emp-config
  namespace: flagger
  labels:
    app: employees
data:
  MYSQL_LB: mysql-db-svc
  VERSION_SERVICE: version-svc
  APP_ENVIRONMENT: production